### ISSUE TITLE
Problems on 14' version of laptop with 'keyboard', 'RedmiBook drivers'  parts of the script

### ISSUE THREAD

**Issue by mikethefirst0** [vrolife/modern_laptop#14]
![16613702721651807101431496909250](https://user-images.githubusercontent.com/49788524/186509134-74679b2f-f67f-46ba-9a0f-8faa28f5170c.jpg)

1)first problem about keyboard'script
"unsupported bios" is that version ".(picture 1)
Though I havethe latest RMARB5B0P0B0B
version of bios, there is still issue.
There is a misspelling bug.
'cause the same mistake in ' supported by the models' bios version is written "RMARB5B0P0808" is instead of "RMARB5B0P0B0B" when it says about 14 inch model . (picture 2)
![IMG_20220824_225516](https://user-images.githubusercontent.com/49788524/186512745-42be6cd1-534d-4219-84f5-52c779c68312.jpg)

I forked your repo and changed the name and it has started working

2) 'RedmiBook part' (picture 3)
![16613715486301197508607111668111](https://user-images.githubusercontent.com/49788524/186513026-93f77be0-93e5-4e03-b8a4-7015435e2c59.jpg)

Maybe also misspelled "redmibook_*". It's better to write in the code 'redmibook_kdb_backlight 1.0.4'

**Comment by mikethefirst0** [comment]
![16613710177427108596392917394318](https://user-images.githubusercontent.com/49788524/186511344-45ceade9-af78-43ea-81cb-066a9890a6f4.jpg)

1

![16613710498243654227297036420348](https://user-images.githubusercontent.com/49788524/186511443-ef236e6d-7ec1-4150-8937-2a1938cf6f90.jpg)
2

![IMG_20220824_225516](https://user-images.githubusercontent.com/49788524/186511529-7a0cc37a-dd8d-4f17-825c-8effb8c8f9f5.jpg)

**Comment by vrolife** [comment]
RMARB5B0P0808 is an earlier version. 15 inch model also have BIOS RMARB5B0P0808, but before I wrote these drivers, I have upgraded to RMARB5B0P0A0A.

add RMARB5B0P0808 for TM2107 https://github.com/vrolife/modern_laptop/commit/06fea2227f8f77c84607c21f32024a735f4429ff

remove "redmibook_*" https://github.com/vrolife/modern_laptop/commit/b14141c279c05bf1179099818a7ce80291438e95

**Comment by mikethefirst0** [comment]
1) maybe you got me wrong.
I mean that 'RMARB5B0P0B0B' is right name. But it is misspelled like 'RMARB5B0P0808' and (8 instead of B) do code doesn't work. But B makes work perfect. Tried on my own laptop

**Comment by mikethefirst0** [comment]
![16614307757528570440798910113350](https://user-images.githubusercontent.com/49788524/186665579-b1fc252c-04ff-4e99-b292-f5641c958b36.jpg)
Thank you for caring

But there still a problem even after a fix .

**Comment by mikethefirst0** [comment]
And it's not a bug, but request. Can you add Fedora support?

**Comment by vrolife** [comment]
RMARB5B0P0B0B -> RMARB4B0P0B0B
https://github.com/vrolife/modern_laptop/commit/1a87a960de34e39a2fd11f855a9a97a0bed694ad https://github.com/vrolife/modern_laptop/commit/909155f9a597dbdb34731170310c39bca3b44037

New branch for fedora https://github.com/vrolife/modern_laptop/tree/fedora .

**Comment by mikethefirst0** [comment]
Hm, it's strange, but that didn't help.
![PXL_20220825_170036375 MP](https://user-images.githubusercontent.com/49788524/186685417-c0021d7d-ba9e-490c-a2d8-5b5f64c873fc.jpg)
It seems like I do everything right. This is my bios information 
![PXL_20220825_165810099 MP](https://user-images.githubusercontent.com/49788524/186685639-109d0354-4fb9-484c-90fd-8102e245a941.jpg)

May be, I do something wrong

**Comment by vrolife** [comment]
In first picture , `git clone ...` command failed
