### ISSUE TITLE
`update-initramfs` in the `fedora` branch

### ISSUE THREAD

**Issue by aimzieslol** [vrolife/modern_laptop#17]
Fedora doesn't have the `update-intramfs` tool. Instead, I believe it uses `dracut` but I'm not sure of the syntax.

**Comment by vrolife** [comment]
There is no installation script that calls "update-intrmfs". Can you post the error log?

**Comment by aimzieslol** [comment]
It's this file:

```
modern_laptop/fixes/disable-PSR/install.sh
```

The line is the last one:

```
update-initramfs -k all -u
```

**Comment by vrolife** [comment]
Fixed https://github.com/vrolife/modern_laptop/commit/c8da709bb70e53b58500b500a25221a50c3750f7

**Comment by vrolife** [comment]
> Manjaro/Arch is also having this problem with the disable-psr script, AFAIK it uses `mkinitcpio` instead

Thank you for your feedback. `disable-PSR` installation script now supports Archlinux/Manjaro. https://github.com/vrolife/modern_laptop/blob/c26a3fb17b6e0bff0b7274a5fdd0ce6df702c8ee/fixes/disable-PSR/install.sh
