### ISSUE TITLE
USB C displayport acting strange

### ISSUE THREAD

**Issue by Vliro** [vrolife/modern_laptop#21]
My usb C over PD was not working. I had to enable iommu=soft to get it working. This is current arch kernel (5.19.6 I think). What is the cause of this issue, as iommu=soft can cause performance issues?

**Comment by vrolife** [comment]
In my laptop(5.17.0-1016-oem), `sudo dmesg|grep DMA`
```
[    0.319021] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
```
iommu=soft is the default behavior.
AMD document says it is `expensive`
[IOMMU Overview](https://www.amd.com/system/files/TechDocs/48882_IOMMU.pdf)

**Comment by vrolife** [comment]
Someone solved this problem by adding "pci=noats" kernel option on Ryzen 3900.
https://www.reddit.com/r/linuxquestions/comments/k3w9zy/has_anyone_gotten_their_ryzen_hardware_iommu_to/

**Comment by vrolife** [comment]
After some research, I think `iommu=soft` does not affect amdgpu. amdgpu uses a dedicated "iommu_v2" module. So this option may not be that `expensive`

**Comment by aimzieslol** [comment]
@vrolife If I don't intend to run any virtualization software on the machine, should I *not* use `pci=noats`?

**Comment by vrolife** [comment]
`pci=noats` affects DMA mechanism, not virtualization. If any PCI device is not recognized, try this option `pci=noats`, if everything working, just keep the default value.
