### ISSUE TITLE
Fingerprint & Ubuntu 22.10

### ISSUE THREAD

**Issue by lispad** [vrolife/modern_laptop#28]
In current daily build of Ubuntu 22.10 the opencv lib got updated to 4.6.0, and `fingerpp3` fails to start, because cannot open shared libraries with version 4.5d.
Could you, please, provide source for fingerpp, so it could be compiled with new libraries, or update binary?

**Comment by vrolife** [comment]
At present, the source code depends on a proprietary library, so the source code cannot be opened. But this problem will be solved soon.
The binary file for Ubuntu 22.10 is here https://github.com/vrolife/modern_laptop/commit/a51f8c64b5c42c7a58d0d9447da60aab2a0da729

**Comment by lispad** [comment]
Thanks a lot! It works fine.
