### ISSUE TITLE
主键盘的回车(36)触发的是小键盘的回车(104) 键码有误

### ISSUE THREAD

**Issue by puzzle9** [vrolife/modern_laptop#3]
# 演示
- `/usr/bin/xev`
- [键盘按键测试 https://keyboard.bmcx.com/](https://keyboard.bmcx.com/)

### 主键盘区
```
KeyPress event, serial 45, synthetic NO, window 0x3600001,
    root 0x845, subw 0x0, time 703078, (106,99), root:(156,209),
    state 0x10, keycode 104 (keysym 0xff8d, KP_Enter), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

### 主键盘区
```
KeyPress event, serial 47, synthetic NO, window 0x3600001,
    root 0x845, subw 0x0, time 746296, (596,1023), root:(646,1133),
    state 0x10, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

### 小键盘区
```
KeyPress event, serial 47, synthetic NO, window 0x3600001,
    root 0x845, subw 0x0, time 769660, (408,407), root:(458,517),
    state 0x10, keycode 104 (keysym 0xff8d, KP_Enter), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

# 影响软件
- `fcitx` 在中文并且候选框有字的时候 按回车会触发搜索

**Comment by vrolife** [comment]
证实确实有这个问题。经分析，这是由于ENTER键从主板传过来的扫描码是0x9C，这个扫描码默认映射KP_Enter键，小米工程师太不讲究了。至于受影响的软件，我这kubuntu+fcitx5没有受到影响。想变更这个默认行为的话，可以往文件/etc/udev/hwdb.d/90-kpenter2enter-keyboard.hwdb写入以下两行内容来将kpenter键映射为enter键盘
`
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnTIMI:pnRedmiBookPro152022:pvr*
    KEYBOARD_KEY_9c=enter
`
如果你的机型不是RedmiBookPro152022，运行以下命令查看具体型号。型号不对则文件不生效
`
evemu-describe /dev/input/event2 |grep DMI # /dev/input/event2 应当为AT Translated Set 2 keyboard
`
参考https://wiki.archlinux.org/title/map_scancodes_to_keycodes
