### ISSUE TITLE
linux kernel `5.19.11`  发布后 键盘可以正常使用啦

### ISSUE THREAD

**Issue by puzzle9** [vrolife/modern_laptop#30]
- https://lore.kernel.org/all/20220712020058.90374-1-gch981213@gmail.com/

**Comment by vrolife** [comment]
是的，不用等6.x了

**Comment by puzzle9** [comment]
不知道`6.x`那个版本后 麦克风也可以直接用了

**Comment by puzzle9** [comment]
> 是的，不用等6.x了

https://github.com/torvalds/linux/commit/a9c4a912b7dc7ff922d4b9261160c001558f9755

在 `6.4.5` 之后 又失效了

**Comment by aqssxlzc** [comment]
😂what a  tragedy.

puz_zle ***@***.***> 于2023年8月2日周三 14:49写道：
