### ISSUE TITLE
8852 installation broken 

### ISSUE THREAD

**Issue by Vliro** [vrolife/modern_laptop#31]
Hi, trying to install rtl8852be but it freezes the entire computer, spawning 1000s of cc processes. How to fix the build? As via dkms this breaks the upgrade of the kernel

**Comment by vrolife** [comment]
Fixed https://github.com/vrolife/modern_laptop/commit/69407c9c905aca9ed48d730207a0d43779c0cb13
Concurrent build jobs consume all memory and CPU time
