### ISSUE TITLE
Support for BIOS_VERSION RMARB4B0P0C0C

### ISSUE THREAD

**Issue by Asscention** [vrolife/modern_laptop#33]
Redmi Book Pro 14 2022 Ryzen BIOS version RMARB4B0P0C0C
keyboard dos not work

**Comment by vrolife** [comment]
Please provide this file `/sys/firmware/acpi/tables/DSDT`

**Comment by Asscention** [comment]
file:///home/asroe/Documents/DSDT

**Comment by Asscention** [comment]
[Uploading DSDT.txt…]()

**Comment by Asscention** [comment]
[DSDT.txt](https://github.com/vrolife/modern_laptop/files/9718074/DSDT.txt)

**Comment by Asscention** [comment]
after i turn off the secure boot it is works well :)

**Comment by vrolife** [comment]
Your DSDT table is the same as the old version. The ACPI patch should works without any modification. So I just make a soft link to the old version. https://github.com/vrolife/modern_laptop/commit/fafaeef4825512bc80f4305502def4a4f5771a0d
