### ISSUE TITLE
外接显示器时，内置屏幕刷新率会降到60Hz

### ISSUE THREAD

**Issue by szmcdull** [vrolife/modern_laptop#35]
redmiboook pro15 2022

**Comment by szmcdull** [comment]
虽然设置里还是90Hz，但实际效果就是60，改成90再改成60还是没有效果

**Comment by vrolife** [comment]
我这没有外置显示器可供测试。你可以试试切换到wayland有没有用。

**Comment by szmcdull** [comment]
> 我这没有外置显示器可供测试。你可以试试切换到wayland有没有用。

用wayland之后刷新率好了，但是几乎所有东西都变模糊了T_T

**Comment by vrolife** [comment]
变模糊是XWayland的原因，把受影响的软件设置使用纯wayland后端即可

**Comment by szmcdull** [comment]
> 变模糊是XWayland的原因，把受影响的软件设置使用纯wayland后端即可

不是很懂这个怎么弄，暂时关闭显示缩放，改用字体DPI就好了，虽然plasma推荐用前者

**Comment by vrolife** [comment]
不打游戏60Hz也够用吧。改字体DPI界面看起来挺诡异的。

**Comment by szmcdull** [comment]
还好，除了有些窗口每次打开默认会比较小，有的甚至显示还更正常，比起X11缩放模式。60Hz总感觉卡卡的
