### ISSUE TITLE
Kernel panics running Minecraft dev

### ISSUE THREAD

**Issue by Vliro** [vrolife/modern_laptop#36]
Running a Java 18 session via gradle, running Minecraft, and it kernel panics constantly. Fairly certain BIOS version RMARB5B0P0B0B. It always happens eventually, and panics after at most a few minutes. Is this a known Rembrandt issue?

**Comment by vrolife** [comment]
Could you please provide log file `/var/log/dmesg` and  `/var/log/dmesg.0`?

**Comment by Vliro** [comment]
https://justpaste.it/86kbr

Here is output of sudo dmesg > dmesg.log

**Comment by Vliro** [comment]
It also happens playing Minecraft (outside dev), so I assume the issue is Java. Quite strange.

**Comment by vrolife** [comment]
Add the kernel parameter `panic=20` to your bootloader (grub or grub2). Linux will automatically reboot after a kernel panic.
After a reboot, the file `/var/log/dmesg.0` should contain panic information. Please provide this file.

**Comment by Vliro** [comment]
I dont have dmesg.log on arch, it is only persisted via journalctl. Would that also work?

**Comment by vrolife** [comment]
On archlinux, try this command `journalctl -b-1 -k`

**Comment by Vliro** [comment]
Unfortunately there are no panic logs there, even after setting boot parameter.

**Comment by Vliro** [comment]
I can say it is very likely a GPU issue. I was attempting to recreate the panic, running programs and switching to tty(serial output). Nothing happened, but when I switched back via CTRL ALT F2 I got an immediate panic. It is unfortunately very hard to say anything more, but it always panics.

**Comment by vrolife** [comment]
I had met same bug in 5.17, and it is hard to reproduce.
Can your introduce your mod development environment? I want to reproduce the panic.

**Comment by Vliro** [comment]
https://github.com/GregTech-Intergalactical/GregTech -- Top level repo - branch fabric-1.18
https://github.com/GregTech-Intergalactical/AntimatterAPI -- Subfolder AntimatterAPI in GregTech - branch fabric-1.18
https://github.com/GregTech-Intergalactical/TesseractAPI -- Subfolder TesseractAPI in AntimatterAPI - branch dev-1.18

`git clone -b fabric-1.18 https://github.com/GregTech-Intergalactical/GregTech && cd GregTech && git clone -b fabric-1.18 https://github.com/GregTech-Intergalactical/AntimatterAPI && cd AntimatterAPI && git clone https://github.com/GregTech-Intergalactical/TesseractAPI`
So GregTech
         AntimatterAPI
               TesseractAPI
Then just 
`./gradlew :forge:runClient`
in top level directory, which should start the environment given Java 17+.

Lastly, to further stress my computer I started an editor (intellij, java) in the same folder, and, to enable video hardware acceleration I activated a YouTube stream. Almost always, within 5 minutes I got a kernel panic.

**Comment by Vliro** [comment]
It is not a java issue, definitely gpu issue. Segfault during counter strike.

**Comment by Vliro** [comment]
`Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 0000000045f535b8 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 000000005e04a4c8 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 000000005fdbaff1 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 0000000045f535b8 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 000000005e04a4c8 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 000000005fdbaff1 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
Oct 21 18:37:03 albert-laptop kernel: amdgpu 0000:04:00.0: amdgpu: 0000000045f535b8 pin failed
Oct 21 18:37:03 albert-laptop kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
`

Got this!

**Comment by vrolife** [comment]
10月 21 21:38:58 hostname kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
10月 21 21:38:58 hostname kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma0 timeout, signaled seq=805427, emitted seq=805429
10月 21 21:38:58 hostname kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
10月 21 21:38:58 hostname kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset begin!
10月 21 21:38:58 hostname kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, signaled seq=5539792, emitted seq=5539795
10月 21 21:38:58 hostname kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process RDD Process pid 4776 thread firefox-bi:cs0 pid 4799
10月 21 21:38:58 hostname kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset begin!
10月 21 21:38:58 hostname kernel: amdgpu 0000:04:00.0: amdgpu: Bailing on TDR for s_job:4e91bf, as another already in progress
10月 21 21:38:59 hostname kernel: amdgpu 0000:04:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
10月 21 21:38:59 hostname kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KGQ disable failed
10月 21 21:38:59 hostname kernel: amdgpu 0000:04:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
10月 21 21:38:59 hostname kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KCQ disable failed
10月 21 21:38:59 hostname kernel: [drm:gfx_v10_0_cp_gfx_enable.isra.0 [amdgpu]] *ERROR* failed to halt cp gfx
10月 21 21:38:59 hostname kernel: amdgpu 0000:04:00.0: amdgpu: MODE2 reset
10月 21 21:38:59 hostname kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset succeeded, trying to resume
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: RAS: optional ras ta ucode is not available
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: RAP: optional rap ta ucode is not available
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: SMU is resuming...
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: SMU is resumed successfully!
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 5 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 6 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 7 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 8 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 9 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 10 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring kiq_2.1.0 uses VM inv eng 11 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring vcn_dec_0 uses VM inv eng 0 on hub 1
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring vcn_enc_0.0 uses VM inv eng 1 on hub 1
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring vcn_enc_0.1 uses VM inv eng 4 on hub 1
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: ring jpeg_dec uses VM inv eng 5 on hub 1
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: recover vram bo from shadow start
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: recover vram bo from shadow done
10月 21 21:39:00 hostname kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset(2) succeeded!
10月 21 21:39:00 hostname kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
10月 21 21:45:52 hostname kernel: amdgpu 0000:04:00.0: amdgpu: 00000000c15574c3 pin failed
10月 21 21:45:52 hostname kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
10月 21 21:46:23 hostname kernel: amdgpu 0000:04:00.0: amdgpu: 00000000152e2bb3 pin failed
10月 21 21:46:23 hostname kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12
10月 21 21:46:53 hostname kernel: amdgpu 0000:04:00.0: amdgpu: 00000000152e2bb3 pin failed
10月 21 21:46:53 hostname kernel: [drm:dm_plane_helper_prepare_fb [amdgpu]] *ERROR* Failed to pin framebuffer with error -12

I got similar error log in 5.17. But this bug quite random. I can't reproduce this bug stably

**Comment by Vliro** [comment]
What distro are you on? Might be arch in this case, since a fresh reinstall of endeavourOS caused same issues.

**Comment by vrolife** [comment]
`Ubuntu 22.04.1 LTS`
This may be a firmware bug.

**Comment by Vliro** [comment]
That's a shame, since that can't easily be fixed?

**Comment by Vliro** [comment]
Although this is definitely kernel version based. During August i played a lot on the laptop without crashes.

**Comment by vrolife** [comment]
It is hard to fix a random bug, and maybe some kernel versions are easy to trigger this bug.
Maybe it is a video decoder/encoder bug. Because in my case firefox media decode process `RDD Process` trigger kernel crash, and in your case you are running YouTube stream.
Can you capture more logs when your kernel crashes? You can install an ssh server that allows you to log in and dump kernel logs when the kernel crashes.

**Comment by Vliro** [comment]
It might be acceleration, but it didn't occur even once in older versions. Around early August. Not sure which kernel then, 5.18?

**Comment by Vliro** [comment]
It is probably not directly related to the kernel, at least what I think, as in newer kernel is not the issue. It must be a package on Arch that has broken the kernel somehow. I am now running 5.18 kernel, which should be the one used by Arch back in August, yet I am still experiencing kernel panics; back then I had no such issues and could run GPU intensive applications all day.

**Comment by Vliro** [comment]
`dmesg-efi-166655918212001:
Oops#1 Part12
<5>[    7.576481] audit: type=1006 audit(1666558946.701:70): pid=730 uid=0 old-auid=4294967295 auid=1000 tty=(none) old-ses=4294967295 ses=2 res=1
<44>[    7.688176] systemd-journald[370]: File /var/log/journal/de04fc7bf97d4823a2cb7d26e0d572c0/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
<6>[   12.910492] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
<4>[   12.927341] kauditd_printk_skb: 19 callbacks suppressed
<5>[   12.927345] audit: type=1325 audit(1666558952.051:86): table=firewalld:4 family=1 entries=6 op=nft_register_rule pid=590 comm="firewalld"
<5>[   12.927352] audit: type=1300 audit(1666558952.051:86): arch=c000003e syscall=46 success=yes exit=1396 a0=6 a1=7fff2ba5d680 a2=0 a3=7fff2ba4c52c items=0 ppid=1 pid=590 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="firewalld" exe="/usr/bin/python3.10" key=(null)
dmesg-efi-166655918111001:
Oops#1 Part11
<5>[   12.927355] audit: type=1327 audit(1666558952.051:86): proctitle=2F7573722F62696E2F707974686F6E002F7573722F62696E2F6669726577616C6C64002D2D6E6F666F726B002D2D6E6F706964
<5>[   13.970099] audit: type=1131 audit(1666558953.095:87): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
<5>[   17.895204] audit: type=1131 audit(1666558957.021:88): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=user@968 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
<5>[   17.928123] audit: type=1131 audit(1666558957.051:89): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=user-runtime-dir@968 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
dmesg-efi-166655918110001:
Oops#1 Part10
<5>[   33.966825] audit: type=1131 audit(1666558972.505:90): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
<5>[   34.131811] audit: type=1334 audit(1666558972.671:91): prog-id=0 op=UNLOAD
<5>[   34.131818] audit: type=1334 audit(1666558972.671:92): prog-id=0 op=UNLOAD
<5>[   34.131821] audit: type=1334 audit(1666558972.671:93): prog-id=0 op=UNLOAD
<5>[   38.224287] audit: type=1131 audit(1666558976.761:94): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
<5>[   38.358491] audit: type=1334 audit(1666558976.898:95): prog-id=0 op=UNLOAD
<5>[   38.358498] audit: type=1334 audit(1666558976.898:96): prog-id=0 op=UNLOAD
<5>[   38.358500] audit: type=1334 audit(1666558976.898:97): prog-id=0 op=UNLOAD
dmesg-efi-166655918109001:
Oops#1 Part9
<5>[  101.741472] audit: type=1100 audit(1666559040.276:98): pid=3460 uid=1000 auid=1000 ses=3 msg='op=PAM:authentication grantors=pam_faillock,pam_permit,pam_faillock acct="alberts" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
<5>[  101.741581] audit: type=1101 audit(1666559040.276:99): pid=3460 uid=1000 auid=1000 ses=3 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="alberts" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
<5>[  101.742241] audit: type=1110 audit(1666559040.276:100): pid=3460 uid=1000 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
<5>[  101.743611] audit: type=1105 audit(1666559040.280:101): pid=3460 uid=1000 auid=1000 ses=3 msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
dmesg-efi-166655918108001:
Oops#1 Part8
<5>[  101.746828] audit: type=1100 audit(1666559040.283:102): pid=3466 uid=0 auid=1000 ses=3 msg='op=PAM:authentication grantors=pam_rootok acct="root" exe="/usr/bin/su" hostname=? addr=? terminal=/dev/pts/2 res=success'
<5>[  101.746869] audit: type=1101 audit(1666559040.283:103): pid=3466 uid=0 auid=1000 ses=3 msg='op=PAM:accounting grantors=pam_unix acct="root" exe="/usr/bin/su" hostname=? addr=? terminal=/dev/pts/2 res=success'
<5>[  101.747062] audit: type=1103 audit(1666559040.283:104): pid=3466 uid=0 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_rootok acct="root" exe="/usr/bin/su" hostname=? addr=? terminal=/dev/pts/2 res=success'
<5>[  101.747121] audit: type=1105 audit(1666559040.283:105): pid=3466 uid=0 auid=1000 ses=3 msg='op=PAM:session_open grantors=pam_unix acct="root" exe="/usr/bin/su" hostname=? addr=? terminal=/dev/pts/2 res=success'
dmesg-efi-166655918107001:
Oops#1 Part7
<5>[  110.470065] audit: type=1131 audit(1666559049.006:106): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-pstore comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
<5>[  110.514761] audit: type=1130 audit(1666559049.050:107): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-pstore comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
<1>[  241.659871] BUG: kernel NULL pointer dereference, address: 0000000000000000
<1>[  241.659880] #PF: supervisor write access in kernel mode
<1>[  241.659883] #PF: error_code(0x0002) - not-present page
<6>[  241.659886] PGD 0 P4D 0 
<4>[  241.659890] Oops: 0002 [#1] PREEMPT SMP NOPTI
<4>[  241.659893] CPU: 11 PID: 0 Comm: swapper/11 Tainted: G           OE      6.0.2-arch1-1 #1 50c0f0880a1bf780734fcafd72b58c22e0d25b99
<4>[  241.659898] Hardware name: TIMI Redmi Book Pro 15 2022/TM2113, BIOS RMARB5B0P0C0C 08/24/2022
dmesg-efi-166655918106001:
Oops#1 Part6
<4>[  241.659900] RIP: 0010:__memset+0x28/0x40
<4>[  241.659909] Code: 00 00 f3 0f 1e fa 0f 1f 44 00 00 49 89 f9 48 89 d1 83 e2 07 48 c1 e9 03 40 0f b6 f6 48 b8 01 01 01 01 01 01 01 01 48 0f af c6 <f3> 48 ab 89 d1 f3 aa 4c 89 c8 c3 cc cc cc cc 66 0f 1f 84 00 00 00
<4>[  241.659911] RSP: 0018:ffffb745c0488e38 EFLAGS: 00010212
<4>[  241.659914] RAX: 0000000000000000 RBX: ffffb745c8df5310 RCX: 0000000000000598
<4>[  241.659917] RDX: 0000000000000004 RSI: 0000000000000000 RDI: 0000000000000000
<4>[  241.659918] RBP: ffffb745c8dee000 R08: 00000000000c2a20 R09: 0000000000000000
<4>[  241.659920] R10: 0000000000003b32 R11: 0000000000000002 R12: ffffb745c8df5310
<4>[  241.659921] R13: ffff98030599bd01 R14: ffffb745c8dee008 R15: 0000000000000000
<4>[  241.659923] FS:  0000000000000000(0000) GS:ffff98060e8c0000(0000) knlGS:0000000000000000
<4>[  241.659925] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
<4>[  241.659927] CR2: 0000000000000000 CR3: 000000028fe10000 CR4: 0000000000750ee0
<4>[  241.659929] PKRU: 55555554
dmesg-efi-166655918005001:
Oops#1 Part5
<4>[  241.659930] Call Trace:
<4>[  241.659933]  <IRQ>
<4>[  241.659941]  _rtw_memset+0x10/0x15 [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660069]  enqueue_idle_rx_buf+0x38/0x9b [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660210]  phl_release_target_rx_buf+0x5b/0x81 [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660320]  phl_recycle_rx_buf+0x36/0x4d [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660446]  rtw_phl_return_rxbuf+0x1c/0x26 [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660555]  rtw_free_recvframe+0x35/0xaf [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660670]  rtw_core_rx_process+0x89/0x12a [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660779]  phl_event_indicator+0x6a/0x7f [8852be 169fe381c8e49aae26c533380bd3f9da42a92e4f]
<4>[  241.660835]  tasklet_action_common.constprop.0+0x132/0x140
<4>[  241.660840]  __do_softirq+0xd3/0x2ca
<4>[  241.660845]  __irq_exit_rcu+0xb7/0xe0
<4>[  241.660846]  common_interrupt+0x86/0xa0
<4>[  241.660850]  </IRQ>
dmesg-efi-166655918004001:
Oops#1 Part4
<4>[  241.660851]  <TASK>
<4>[  241.660851]  asm_common_interrupt+0x26/0x40
<4>[  241.660854] RIP: 0010:cpuidle_enter_state+0xe2/0x420
<4>[  241.660857] Code: 00 00 31 ff e8 6f 0c 7d ff 45 84 ff 74 16 9c 58 0f 1f 40 00 f6 c4 02 0f 85 25 03 00 00 31 ff e8 14 cb 83 ff fb 0f 1f 44 00 00 <45> 85 f6 0f 88 85 01 00 00 49 63 d6 48 8d 04 52 48 8d 04 82 49 8d
<4>[  241.660858] RSP: 0018:ffffb745c021fe90 EFLAGS: 00000246
<4>[  241.660859] RAX: ffff98060e8f2d40 RBX: ffff980305c24000 RCX: 0000000000000000
<4>[  241.660860] RDX: 000000000000000b RSI: fffffffe3e5b4835 RDI: 0000000000000000
<4>[  241.660861] RBP: 0000000000000003 R08: 0000000000000002 R09: 0000000028135791
<4>[  241.660861] R10: 0000000000000018 R11: 0000000000000118 R12: ffffffffa474b940
<4>[  241.660862] R13: 00000038440b74fb R14: 0000000000000003 R15: 0000000000000000
<4>[  241.660865]  cpuidle_enter+0x2d/0x40
<4>[  241.660866]  do_idle+0x1ed/0x270
<4>[  241.660870]  cpu_startup_entry+0x1d/0x20
<4>[  241.660871]  start_secondary+0x115/0x140
<4>[  241.660875]  secondary_startup_64_no_verify+0xe5/0xeb
dmesg-efi-166655918003001:
Oops#1 Part3
<4>[  241.660883]  </TASK>
<4>[  241.660884] Modules linked in: snd_seq_dummy snd_hrtimer snd_seq snd_seq_device nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 nf_tables nfnetlink snd_ctl_led intel_rapl_msr intel_rapl_common hid_logitech_hidpp snd_soc_dmic snd_acp6x_pdm_dma edac_mce_amd snd_soc_acp6x_mach(OE) hid_sensor_als snd_sof_amd_renoir hid_sensor_trigger btusb(OE) snd_sof_amd_acp btrtl(OE) industrialio_triggered_buffer kvm_amd snd_sof_pci btbcm kfifo_buf hid_sensor_iio_common joydev mousedev btintel snd_sof industrialio kvm snd_sof_utils btmtk snd_hda_codec_conexant vfat snd_hda_codec_generic irqbypass amdgpu fat snd_soc_core bluetooth hid_multitouch snd_hda_codec_hdmi hid_logitech_dj hid_sensor_hub ledtrig_audio crct10dif_pclmul snd_compress snd_hda_intel crc32_pclmul uvcvideo ac97_bus polyval_clmulni snd_intel_dspcfg snd_pcm_dmaengine wmi_bmof snd_intel_sdw_acpi polyval_generic
dmesg-efi-166655918002001:
Oops#1 Part2
<4>[  241.660941]  redmibook_wmi(OE) ecdh_generic snd_rpl_pci_acp6x crc16 snd_hda_codec gpu_sched snd_acp_pci gf128mul videobuf2_vmalloc snd_hda_core ghash_clmulni_intel videobuf2_memops snd_pci_acp6x redmibook_kbd_backlight(OE) 8852be(OE) drm_buddy aesni_intel snd_pci_acp5x snd_hwdep videobuf2_v4l2 crypto_simd drm_ttm_helper videobuf2_common snd_pcm cryptd snd_rn_pci_acp3x ttm tpm_crb cfg80211 snd_acp_config ucsi_acpi rapl videodev snd_timer drm_display_helper snd_soc_acpi typec_ucsi tpm_tis sp5100_tco snd pcspkr typec mc usbhid tpm_tis_core k10temp ccp amd_sfh cec soundcore snd_pci_acp3x i2c_piix4 rfkill roles mac_hid video wmi tpm i2c_hid_acpi rng_core i2c_hid acpi_tad acpi_cpufreq pkcs8_key_parser crypto_user fuse bpf_preload ip_tables x_tables btrfs blake2b_generic libcrc32c crc32c_generic xor raid6_pq serio_raw atkbd rtsx_pci_sdmmc libps2 mmc_core vivaldi_fmap nvme nvme_core xhci_pci crc32c_intel i8042 rtsx_pci xhci_pci_renesas nvme_common serio
dmesg-efi-166655918001001:
Oops#1 Part1
<4>[  241.660993] Unloaded tainted modules: amd64_edac():1 amd64_edac():1 amd64_edac():1 amd64_edac():1 amd64_edac():1 amd64_edac():1 amd64_edac():1 amd64_edac():1 pcc_cpufreq():1 amd64_edac():1 amd64_edac():1 pcc_cpufreq():1 amd64_edac():1 fjes():1 pcc_cpufreq():1 amd64_edac():1 fjes():1 pcc_cpufreq():1 fjes():1 pcc_cpufreq():1 amd64_edac():1 pcc_cpufreq():1 amd64_edac():1 fjes():1 amd64_edac():1 fjes():1 pcc_cpufreq():1 amd64_edac():1 fjes():1 pcc_cpufreq():1 pcc_cpufreq():1 fjes():1 fjes():1 pcc_cpufreq():1 pcc_cpufreq():1 fjes():1 pcc_cpufreq():1 fjes():1 pcc_cpufreq():1 fjes():1 pcc_cpufreq():1 pcc_cpufreq():1 fjes():1 pcc_cpufreq():1 fjes():1 fjes():1
<4>[  241.661036] CR2: 0000000000000000
<4>[  241.661038] ---[ end trace 0000000000000000 ]---
`

Kernel panic log!

**Comment by Vliro** [comment]
Seems that RTW is causing the panic

**Comment by vrolife** [comment]
RTW is the driver of RTL8852BE.
In my laptop, I had replace RTL8852BE with AX210, and the GPU still crash.
RTL8852BE on linux has many bugs. It is highly recommended to replace it with AX200/AX210.

**Comment by Vliro** [comment]
Fixed with new wifi card.
