### ISSUE TITLE
ICC Profile for Display?

### ISSUE THREAD

**Issue by virtualritz** [vrolife/modern_laptop#38]
Does anyone have an ICC profile for the display of the 22 edition?

I found one for the [21](https://www.notebookcheck.net/Xiaomi-RedmiBook-Pro-15-2021-in-review-Affordable-laptop-with-strong-features.545905.0.html) edition [here](https://www.notebookcheck.net/uploads/tx_nbc2/Redmi.icm).

**Comment by vrolife** [comment]
Redmi Book Pro 15 2022 Ryzen
[SRGB_Cali.zip](https://github.com/vrolife/modern_laptop/files/9839396/SRGB_Cali.zip)

**Comment by virtualritz** [comment]
Thanks heaps! Maybe this could be added to the repo & mentioned in the `README`? :)
