### ISSUE TITLE
after make install:  Hunk #3 FAILED at 1586. 

### ISSUE THREAD

**Issue by longwallstreet** [vrolife/modern_laptop#4]
![Screenshot from 2022-07-17 16-59-12](https://user-images.githubusercontent.com/34297812/179391477-932e7a82-5482-4217-840d-b8125f6da26b.png)

**Comment by vrolife** [comment]
pull https://github.com/vrolife/modern_laptop/commit/208f34a679af2c02230d73d67d325f8219bcc729 and try again
