### ISSUE TITLE
安装 rtl8852be 时出错 

### ISSUE THREAD

**Issue by 645418484** [vrolife/modern_laptop#43]
安装 rtl8852be 时出现modprobe: ERROR: could not insert '8852be': Invalid argument

在终端执行 sudo /bin/sh install.sh rtl8852be 出现以上问题
-操作系统:
linux ray-Redmi-Book-Pro-14-2022 5.17.0-1021-oem #22-Ubuntu SMP PREEMPT Wed Nov 2 17:28:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

-环境
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubunt
[Uploading dmesg.log…]()
u.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

log 
/var/log/dmesg：

**Comment by 645418484** [comment]
[Uploading dmesg.log…]()

**Comment by vrolife** [comment]
看不到dmesg.log. 请重新上传。
另外rtl8852be有蛮多bug的，建议更换为AX210/AX200网卡（有可能影响保修）

**Comment by 645418484** [comment]
> 看不到dmesg.log. 请重新上传。 另外rtl8852be有蛮多bug的，建议更换为AX210/AX200网卡（有可能影响保修）
ok
[Uploading dmesg.log…]()

如果我更换了ax210 我应该用什么网卡驱动呢？
如果还是看不到的话麻烦留个邮箱什么的吧 我这边不知道为什么一直都是上传中

**Comment by 645418484** [comment]
[dmesg.zip](https://github.com/vrolife/modern_laptop/files/9991061/dmesg.zip)
@vrolife   终于上传上来了  麻烦您了

**Comment by 645418484** [comment]
ax200 安排上了 明天下午到货 💯

**Comment by vrolife** [comment]
dmesg里没有啥有用的信息。应该安装驱动失败后再取dmes log.
ax200 在 Linux 5.4后是不用额外装驱动的，内核自带。换网卡的时候记得扣电池，免得烧东西。

**Comment by 645418484** [comment]
> dmesg里没有啥有用的信息。应该安装驱动失败后再取dmes log. ax200 在 Linux 5.4后是不用额外装驱动的，内核自带。换网卡的时候记得扣电池，免得烧东西。

okok 那就不折腾了 到货了直接换好了   谢谢大佬
