### ISSUE TITLE
(RedmiBook pro 14 2022)I dont now how to start fingerprint

### ISSUE THREAD

**Issue by babenychka** [vrolife/modern_laptop#48]
![Снимок экрана от 2022-12-04 23-39-14](https://user-images.githubusercontent.com/111590496/205511686-f687acd2-1054-472c-8c19-1530a2efde5f.png)
I full installed fprint and it work on fedora 37, but dont work in console and lock screen. I think i am not run fprint for other applications.
sry for my english:(

**Comment by vrolife** [comment]
Have you enabled fingerprint authentication in your system? 
If not, run `sudo pam-auth-update`, then select `Fingerprint authentication`

**Comment by babenychka** [comment]
what package should install?
![Снимок экрана от 2022-12-05 10-17-22](https://user-images.githubusercontent.com/111590496/205562770-a7d19896-45ae-452c-b22c-3dabf6646533.png)

**Comment by flamelcadet** [comment]
Use
`sudo authselect current ` 
It should be like this:
```
Profile ID: sssd
Enabled features:
- with-silent-lastlog
- with-mdns4
- with-fingerprint
```
```
sudo -u gdm gsettings list-recursively org.gnome.login-screen
org.gnome.login-screen allowed-failures 3
org.gnome.login-screen banner-message-enable false
org.gnome.login-screen banner-message-text ''
org.gnome.login-screen disable-restart-buttons false
org.gnome.login-screen disable-user-list false
org.gnome.login-screen enable-fingerprint-authentication true
org.gnome.login-screen enable-password-authentication true
org.gnome.login-screen enable-smartcard-authentication false
org.gnome.login-screen fallback-logo ''
org.gnome.login-screen logo '/usr/share/pixmaps/fedora-gdm-logo.png'
```

**Comment by babenychka** [comment]
![Снимок экрана от 2022-12-05 10-26-16](https://user-images.githubusercontent.com/111590496/205564038-c8b6e365-0a57-4d86-9a53-16427bc78232.png)

**Comment by flamelcadet** [comment]
sudo -u gdm gsettings set org.gnome.login-screen enable-fingerprint-authentication true

**Comment by babenychka** [comment]
console write: Key not writable

**Comment by flamelcadet** [comment]
Fedora Workstation with GNOME or KDE?

**Comment by babenychka** [comment]
GNOME

**Comment by flamelcadet** [comment]
sudo authselect select sssd with-silent-lastlog with-mdns4 with-fingerprint

**Comment by babenychka** [comment]
In authselect fprint is enable,but when i want unlock screen, he writes :fingerprint login did not work. try again.Later i cant use fprint

**Comment by flamelcadet** [comment]
`sudo -u gdm gsettings list-recursively org.gnome.login-screen`
Must give:
`org.gnome.login-screen enable-fingerprint-authentication true`
if not - use:
`sudo -u gdm gsettings set org.gnome.login-screen enable-fingerprint-authentication true`

fprintd-pam is installed?
`sudo dnf install fprintd-pam `
