### ISSUE TITLE
RedmiBook pro 14 2022. Cooler settings

### ISSUE THREAD

**Issue by babenychka** [vrolife/modern_laptop#49]
I have RedmiBook pro 14 2022 amd 6600h and use like Windows there and Linux.
Do you know utilities or packages? which can change temperature turn on cooler.I want to my fan turned on not at 40 degrees, but at 45>?
I didnt find any info on the internet about this task

**Comment by vrolife** [comment]
https://blog.csdn.net/vistaup/article/details/120894989

**Comment by babenychka** [comment]
this utility not have config for my model.
Config in utility not work in my model.
Config Xiaomi Mi Book (TM...) blinking, but no work
![image](https://user-images.githubusercontent.com/111590496/205677741-064fe320-999e-416f-93e5-5725fb096a13.png)

**Comment by vrolife** [comment]
https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by babenychka** [comment]
thank you, maybe i will try to create a config file,but now i cant
