### ISSUE TITLE
Xiaomi Book pro 16 2022

### ISSUE THREAD

**Issue by PH7-Jack** [vrolife/modern_laptop#53]
Hey, it's possible to get drivers to the book pro 16 model?

**Comment by vrolife** [comment]
Fingerprint and WIFI drivers may be applicable to Book Pro 16, and others are only applicable to Ryzen platform.

**Comment by PH7-Jack** [comment]
@vrolife even if the processor is i7? My notebook has a i7 instead of a Ryzen

**Comment by vrolife** [comment]
> @vrolife even if the processor is i7? My notebook has a i7 instead of a Ryzen

yes

**Comment by PH7-Jack** [comment]
Great. It has worked for me. Thanks
