### ISSUE TITLE
Patching support for Linux Mint

### ISSUE THREAD

**Issue by kartun83** [vrolife/modern_laptop#58]
**Describe the bug**
Patching is not working on linux mint

**To Reproduce**
1. sudo /bin/sh install.sh acpi 
2. Error message : "Unknown environment"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 22.1
 - Kernel version: Linux kartun-RedmiBook-16 6.1.6-060106-generic #202301141035 SMP PREEMPT_DYNAMIC Sat Jan 14 11:15:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Fix:**
Change: `if test "$ID" = "debian" -o "$ID_LIKE" = "debian"; then`
with 
`if test "$ID" = "debian" -o "$ID_LIKE" = "debian" -o "$ID" = "linuxmint"; then`

**Comment by vrolife** [comment]
🤝 https://github.com/vrolife/modern_laptop/commit/34bd382953a908c12218dfc5e2448a383502f3f6
