### ISSUE TITLE
Wi-Fi not working on the latest kernel, Fedora 37

### ISSUE THREAD

**Issue by Adefey** [vrolife/modern_laptop#60]
**Describe the bug**
The Wi-Fi is not working on redmibook pro 15 2022 ryzen, Fedora Linux, latest kernel, but still works on 6.0.18

**To Reproduce**
1. Power up laptop
2. No available networks at Wi-Fi menu

**Expected behavior**
At Linux 6.0.18 Wi-Fi works fine

**Desktop (please complete the following information):**
 - OS: Fedora Linux 
 - Version 37
 - Kernel version: 6.1.6
 - Environment: 
 
NAME="Fedora Linux"
VERSION="37 (KDE Plasma)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="KDE Plasma"
VARIANT_ID=kde

**Comment by vrolife** [comment]
https://github.com/vrolife/modern_laptop/tree/rtl8852be_linux_6_1

**Comment by Adefey** [comment]
Thank you
