### ISSUE TITLE
[Bug] ArchLinux and fingerprint

### ISSUE THREAD

**Issue by un-couteau** [vrolife/modern_laptop#65]
![image](https://user-images.githubusercontent.com/65289168/215579532-59f53b89-f53a-461a-ae3b-cee4385f8e41.png)

because of the updated opencv in ArchLinux, you have to rebuild the fingerprint.

I tried, but the attempt ended with an error

Too bad there is no PKGBUILD ready

**Comment by vrolife** [comment]
https://github.com/vrolife/modern_laptop/tree/static_ocv_fingerprint_driver
https://github.com/vrolife/modern_laptop/commit/3d1661c662afbee934c2d5d8795f8b118423ad4c

**Comment by un-couteau** [comment]
![image](https://user-images.githubusercontent.com/65289168/216041882-6525782f-4468-4e71-a27d-b0693928ab7a.png)
I'm doing something wrong.

**Comment by vrolife** [comment]
After installing the fingerprint driver from branch [static_ocv_fingerprint_driver](https://github.com/vrolife/modern_laptop/tree/static_ocv_fingerprint_driver), you no longer need opencv.

**Comment by un-couteau** [comment]
![image](https://user-images.githubusercontent.com/65289168/216052664-29ae6fe7-a2e2-4f9d-bcc4-64fd8b5f2b1f.png)
I thought you already filled in the master with changes 

Moved to the branch and now it works, thanks!
![image](https://user-images.githubusercontent.com/65289168/216052861-ba759901-35ba-4675-933d-929bd25a04b5.png)
