### ISSUE TITLE
Redmibook 15 pro 2022 在替换网卡为 AX210 后 acpi 补丁生成的 acpi_override 将使引导失败

### ISSUE THREAD

**Issue by fengwk** [vrolife/modern_laptop#66]
我在为 Redmibook 15 pro 2022  更换网卡后开机发现卡在了启动处，因为我设置了timeout 0，所以看起来像是卡住了，这误导了我，同时困扰了我好几个小时，起初以为是硬件问题，最终发现是`initrd /acpi_override`的原因，去除后就能正确引导，完整的启动配置如下：

```
title ArchLinux
linux /vmlinuz-linux
initrd /amd-ucode.img
initrd /acpi_override
initrd /initramfs-linux.img
options root=PARTUUID=824abb3e-2913-f041-a2e5-b0c6e4251e5e rw resume=UUID=d6e8e1a3-31f0-4bf1-abe5-54811930ab83 ACPI_TABLE_UPGRADE=y
```

这个 issues 或许可以帮助遇到相同问题的人查明原因，另外如果需要在 Redmibook 15 pro 2022 上获取麦克风，除了 acpi 外可以等待 linux 的版本更新，我的补丁已经被合入，另外需要添加以下启动参数：

```
CONFIG_SND_SOC=y CONFIG_SND_SOC_AMD_ACP6x=y CONFIG_SND_SOC_AMD_YC_MACH=y
```

**Comment by vrolife** [comment]
我同样在使用AX210, 能正常启动，我的启动参数多了`acpi_osi=! acpi_osi=Linux`，这也许是关键。这段参数作用是避免关机隨眠SSD Unsafe shutdown 无故增加。希望这些信息有用。

BOOT_IMAGE=/@/boot/vmlinuz-6.1.0-1006-oem root=UUID=97a36921-7ed1-4179-a3ac-0403c237517b ro rootflags=subvol=@ **acpi_osi=! acpi_osi=Linux** quiet splash resume=UUID=bc50adb6-a249-4d92-a2fc-881d870e9219 vt.handoff=7

**Comment by fengwk** [comment]
我尝试了这两个参数，任然没有成功

**Comment by lucashanak** [comment]
Same problem on Redmibook 14 pro. Can't boot to linux after change wifi adapter to AX211. My solution was remove acpi override from GRUB, then I can boot linux and reinstal ACPI patch.
