### ISSUE TITLE
机械革命蛟龙16K键盘无效问题如何解决

### ISSUE THREAD

**Issue by KunSong-L** [vrolife/modern_laptop#70]
机械革命蛟龙16K，7735H+3050版本，在ubuntu20.04和ubuntu 20.04键盘不能使用，仅有调节亮度可用，外界键盘也可以使用。升级到6.1.12内核都不能解决键盘问题，请问一下有什么解决办法吗？
**机型信息**
```
$ dmidecode -s system-manufacturer
MECHREVO
$ dmidecode -s baseboard-product-name
GM6BGEQ
```

**Comment by vrolife** [comment]
尝试安装一个老的内核看看能不能工作。比如`linux oem 5.17 1003` ubuntu 源里能找到这个内核。

**Comment by KunSong-L** [comment]
目前用了5.13.0-30的内核能够正常使用（还有一些小问题就是，在混合模式下亮度还是不能调节，独显直连可以用brigheness controller调节），就是需要禁用系统的自动升级，升级到5.15内核键盘就不能使用了

**Comment by vrolife** [comment]
那我就知道问题所在了。你的这款笔记本键盘中断部分用的是旧的设计，在旧的设计中，内核需要覆盖ACPI中对中断的描述才能使其正常工作。而较新的内核中，如果检测到新的处理器，是没有这个覆盖动作的。解决这个问题的办法有两个，一个是修改内核，另一个是对ACPI打补丁。
修改ACPI的话，可以参考此链接https://zhuanlan.zhihu.com/p/530643928

**Comment by KunSong-L** [comment]
感谢感谢，那这个问题应该就被解决了
