### ISSUE TITLE
ACPI Patch Error

### ISSUE THREAD

**Issue by MalpenZibo** [vrolife/modern_laptop#74]
I tried to install the ACPI Patch with
`sudo ./install.sh acpi`

on the latest main branch but I get thi error
`Unsupported product: TM2119-Xiaomi_Book_Pro_14_2022`

OS: Arch linux
Device: Xiaomi book 14 pro

**Comment by vrolife** [comment]
The ACPI patch needs to be port to TM2119, please provide the ACPI tables generated by `acpidump -b`.

**Comment by MalpenZibo** [comment]
Maybe it's caused by my tentative to install the acpi path changing the `TM2107-Redmi_Book_Pro_14_2022` to make it work (with no luck) on my laptop but right now the `acpidump -b` command returns:
```
Table signature (0x4F324824) is invalid
Could not get ACPI table at index 34, AE_BAD_HEADER
```

I already launched the `uninstall.sh acpi` script to revert my tentative.

In any case, right now everything seems to work ok with the exception of the fingerprint sensor (I tried with the docker driver that work only for the first scan and after that the service crashed) and the internal microphone.

**Comment by MalpenZibo** [comment]
On a fresh arch linux installation the result is:
```
Could not open table file: /sys/firmware/acpi/tables/SSDT4
Could not get ACPI tables, AE_ACCESS
```

**Comment by MalpenZibo** [comment]
Same result on a fresh arch linux installation
```
Table signature (0x4F324824) is invalid
Could not get ACPI table at index 34, AE_BAD_HEADER
```

**Comment by vrolife** [comment]
Here is another way to dump ACPI table `sudo cp /sys/firmware/acpi/tables/DSDT ./dsdt.dat`.

**Comment by MalpenZibo** [comment]
Here's a link to the `dsdt.dat` file https://drive.google.com/file/d/1nmx7xwiJRHZYG7OWSiXQQT0Z-Dusx7gE/view?usp=share_link

**Comment by vrolife** [comment]
Need to know the BIOS version. `dmidecode -t bios |grep Version`

**Comment by MalpenZibo** [comment]
BIOS version: `XMARB4B0P0B0B`

**Comment by vrolife** [comment]
Try this branch. https://github.com/vrolife/modern_laptop/tree/TM2119

**Comment by MalpenZibo** [comment]
Thank you so much, you're a hero!!

I tried (I have systemd-boot).
`NO_GRUB=1 sudo ./install.sh acpi` and then I add to `/boot/loader/entries/my_entry.conf`
```
initrd  /acpi_override
options ... acpi_osi=! acpi_osi=Linux
```

After a reboot, the internal microphone still doesn't work so I think that something still doesn't work

**Comment by vrolife** [comment]
Could it be "initrd /boot/acpi_override"? I know nothing about systemd-boot.

**Comment by vrolife** [comment]
`Secure Boot ` will prevent Linux from loading ACPI patches, you may need to disable `Secure Boot`.

**Comment by MalpenZibo** [comment]
Secure boot Is already disabled. 

Now I tried with /boot/acpi_override but the system doesn't start anymore (I've to fix It)
The error is: "Error preparing initrd: Not found"

**Comment by MalpenZibo** [comment]
Anyway, misconfig is fixed. 
I think that the correct configuration is `/acpi_override` and something changes if I set that parameter (screen brightness cannot be changed anymore).

**Comment by vrolife** [comment]
Check whether ACPI table is correctly overwritten `sudo dmesg|grep -i acpi|grep -i override`

**Comment by MalpenZibo** [comment]
Ok! I can confirm that the patch is applied and the internal microphone now works. The only downside is that the screen brightness cannot be changed, without the patch the screen brightness can be changed but the internal microphone doesn't work.

`sudo dmesg|grep -i acpi|grep -i override` output
```
[    0.000000] Command line: initrd=\acpi_override initrd=\amd-ucode.img initrd=\initramfs-linux.img cryptdevice=PARTUUID=dacc3f71-e359-49a3-935f-1d0053247332:luksdev root=/dev/mapper/luksdev zswap.enabled=0 rw rootfstype=btrfs loglevel=3 acpi_osi=! acpi_osi=Linux
[    0.003712] ACPI: Table Upgrade: override [DSDT-XMCC  -XMCC2119]
[    0.003713] ACPI: DSDT 0x00000000BAFD7000 Physical table override, new table: 0x00000000AF881000
[    0.026974] Kernel command line: initrd=\acpi_override initrd=\amd-ucode.img initrd=\initramfs-linux.img cryptdevice=PARTUUID=dacc3f71-e359-49a3-935f-1d0053247332:luksdev root=/dev/mapper/luksdev zswap.enabled=0 rw rootfstype=btrfs loglevel=3 acpi_osi=! acpi_osi=Linux
```

system-boot entries:
```
title Arch Linux acpi override (linux)
linux /vmlinuz-linux
initrd /acpi_override # it seems important to place the `/acpi_override` option before the other initrd
initrd /amd-ucode.img
initrd /initramfs-linux.img
options ... acpi_osi=! acpi_osi=Linux
```

**Comment by MalpenZibo** [comment]
Without adding `options ... acpi_osi=! acpi_osi=Linux` both internal microphone and screen brightness seems to work. 

I'll test this setup to understand if cause other problems but for now it seems working well.

**Comment by vrolife** [comment]
`acpi_osi=! acpi_osi=Linux` fix that TM2113 cannot wake up without AC power. If your laptop doesn't have this problem, you may not need this option.

**Comment by MalpenZibo** [comment]
This problem seems not happen on this model.

Thank you so much. Now everything seems working correctly.

**Comment by MalpenZibo** [comment]
This solution stops working. I don't know why (probably some arch linux update) but right now if I try to boot the system using the entry with `initrd /acpi_override` I get a black screen and nothing more.

I'm currently booting the system without the `acpi_override` and with the internal microphone issue.

Do you have some ideas about this new problem?

**Comment by MalpenZibo** [comment]
Fixed with a bios rollback
