### ISSUE TITLE
内核升级到6.3.0-060300-generic 一切硬件工作正常

### ISSUE THREAD

**Issue by Mino9526** [vrolife/modern_laptop#79]
https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.3/amd64/

试了下 键盘 无线网卡 键盘背光 功能键好像都可以不装驱动进行工作了

ps. 23.04的6.2.0-20-generic触摸板工作有问题

**Comment by vrolife** [comment]
你卸载dkms驱动了？

**Comment by Mino9526** [comment]
> 你卸载dkms驱动了？

卸载了

**Comment by vrolife** [comment]
> > 你卸载dkms驱动了？
> 
> 卸载了

看来部分驱动可以标记弃用了

**Comment by zhbotong** [comment]
指纹呢？

**Comment by noxytocin** [comment]
@zhbotong unfortunately the fingerprint is not working on my Manjaro GNOME, linux 6.3.5-2 by default and it's can't be fixed using this repo's fingerprint driver for now.

**Comment by Mino9526** [comment]
> 指纹呢？

指纹不好使 一直没用指纹 忘了这个事 = =

**Comment by puzzle9** [comment]
发现自动亮度好像也可以了
