### ISSUE TITLE
some tips

### ISSUE THREAD

**Issue by Evan7o** [vrolife/modern_laptop#8]
when me switch Ubuntu of win11 by today, my keyboard and WLAN is not work :(
and I try install this repos, but is not work. (used 6PM to 10PM) I'm feeling so bad.
but now all is right !!! the issues is  my BIOS have open **UEFI Secure Boot** , i don't know about that. 
so i want to help others, so share some tips!
1.when you install some dependency before, like make,acpica-tools. you maybe need run apt update. update your cache.
2.if you lost WLAN, you can connect you ANDROID phone, select share network get internet.
3.if you install this repos right but not work, you can check BIOS  **UEFI Secure Boot** option.
4.when I install WLAN driver, get error for ```dkms: command not found ``` so your need install dkms before.

sorry for my English,  my Chinese input is not install. thank you **vrolife**

**Comment by vrolife** [comment]
感谢您的建议。关于网络的建议已经更新到`README.md`中。其他的改进到了`install.sh`脚本中。详情请查看https://github.com/vrolife/modern_laptop/commit/56f46405aceab5be0ba13cdc333ac69009bf2d53
