### ISSUE TITLE
OpenCV 4.8 fingerprint

### ISSUE THREAD

**Issue by flamelcadet** [vrolife/modern_laptop#87]
Hello, 
ArchLinux used OpenCV 4.8 in repo, but fingerprint maked with 4.6 version and vcpkg in fingerprint-ocv used 4.6 version too.
How to build package with 4.8 version or exist another way?
Symlinks does not work, fprintd-enroll just crash after first touch scanner.
Thank u

**Comment by vrolife** [comment]
try this branch https://github.com/vrolife/modern_laptop/tree/static_ocv_fingerprint_driver

**Comment by flamelcadet** [comment]
That`s works for me, thank you!
