### ISSUE TITLE
Can't install fingerprint driver

### ISSUE THREAD

**Issue by Geniucker** [vrolife/modern_laptop#94]
**Describe the bug**
While installing the driver of fingerprint sensor, it produced `No fingerprint sensor detected`.
However when I check `lsusb`, I can get `Bus 001 Device 002: ID 10a5:9201 [unknown] [unknown]`. I'm not sure why it produced "unknown"
Interestingly, `lsusb.py` will give `1-3               10a5:9201 00 1IF  [USB 1.10,   480 Mbps, 100mA] (FPC FPC Sensor Controller L:0001 FW:021.26.2.031)`
After remove the checking code in drivers/fingerprint/install.sh, I successfully installed the driver. But I still can't use the fingerprint sensor. 
commands like `fprintd-verify` will produce "No devices available"

edit: finally fixed
I checked fprintd.services and found it was not properly patched.
After manually modifying `ExecStart=/opt/fingerpp/bin/fingerpp --bus=system --filter-before-ssim=true --min-score=0.3` it works.

**To Reproduce**
```shell
sudo /bin/sh install.sh fingerprint
```

**Expected behavior**
Succussfully install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 39
 - Kernel version: `Linux fedora 6.6.8-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 21 04:01:49 UTC 2023 x86_64 GNU/Linux`
 - Environment: `cat /etc/os-release`
   ```
    NAME="Fedora Linux"
    VERSION="39 (Workstation Edition)"
    ID=fedora
    VERSION_ID=39
    VERSION_CODENAME=""
    PLATFORM_ID="platform:f39"
    PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
    ANSI_COLOR="0;38;2;60;110;180"
    LOGO=fedora-logo-icon
    CPE_NAME="cpe:/o:fedoraproject:fedora:39"
    DEFAULT_HOSTNAME="fedora"
    HOME_URL="https://fedoraproject.org/"
    DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
    SUPPORT_URL="https://ask.fedoraproject.org/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=39
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=39
    SUPPORT_END=2024-11-12
    VARIANT="Workstation Edition"
    VARIANT_ID=workstation
   ```

** Log **
Application error message or command output.
For kernel/driver issue, provide /var/log/dmesg and /var/log/dmesg.0, if both files does not exists, run `journalctl -k > /var/log/dmesg` and `journalctl -b-1 -k > /var/log/dmesg.0` to generate them.

**Comment by vrolife** [comment]
For Debian/Ubuntu, installing `usb.ids` may solve this problem
